import { db, propertiesTable, vendorsTable } from "@workspace/db";

async function seed() {
  console.log("Seeding properties...");

  await db.insert(propertiesTable).values([
    {
      property_name: "Downtown Houston Hotel District",
      city: "Houston",
      metro: "Houston-The Woodlands-Sugar Land",
      state: "TX",
      zip: "77002",
      property_type: "Hotel",
      sub_type: "Full-Service",
      ownership_type: "REIT",
      parking_type: "Structured Garage",
      management_model: "Outsourced",
      payment_model: "Paid - Gated",
      estimated_revenue_potential: "$800K-$1.4M annually",
      demand_drivers: "Convention center, medical center proximity, business travel",
      friction_points: "Valet staffing, peak demand management, revenue leakage",
      notes: "Strong case for dynamic pricing during events",
      featured: true,
      slug: "downtown-houston-hotel-district",
    },
    {
      property_name: "Texas Medical Center Campus",
      city: "Houston",
      metro: "Houston-The Woodlands-Sugar Land",
      state: "TX",
      zip: "77030",
      property_type: "Hospital",
      sub_type: "Academic Medical Center",
      ownership_type: "Non-Profit",
      parking_type: "Mixed - Surface and Structured",
      management_model: "Self-Managed",
      payment_model: "Paid - Gated and Validation",
      estimated_revenue_potential: "$2M-$4M annually",
      demand_drivers: "Patient volume, employee commuter demand, visitor traffic",
      friction_points: "Patient experience sensitivity, staff benefit conflicts, validation abuse",
      notes: "Largest medical complex in the world - parking is a major operational asset",
      featured: true,
      slug: "texas-medical-center-campus",
    },
    {
      property_name: "Uptown Dallas Office Campus",
      city: "Dallas",
      metro: "Dallas-Fort Worth-Arlington",
      state: "TX",
      zip: "75201",
      property_type: "Commercial Real Estate",
      sub_type: "Class A Office",
      ownership_type: "Private Equity",
      parking_type: "Structured Garage",
      management_model: "Outsourced",
      payment_model: "Monthly Leases + Transient",
      estimated_revenue_potential: "$600K-$1.1M annually",
      demand_drivers: "Tenant density, Uptown amenities, weekend event parking",
      friction_points: "Tenant lease negotiation, after-hours access, enforcement",
      notes: "Hybrid monthly/transient model can significantly improve yield",
      featured: true,
      slug: "uptown-dallas-office-campus",
    },
    {
      property_name: "Dallas Medical District Hospital",
      city: "Dallas",
      metro: "Dallas-Fort Worth-Arlington",
      state: "TX",
      zip: "75390",
      property_type: "Hospital",
      sub_type: "Regional Medical Center",
      ownership_type: "Health System",
      parking_type: "Structured Garage",
      management_model: "Outsourced",
      payment_model: "Paid - Gated with Validation",
      estimated_revenue_potential: "$1.5M-$2.5M annually",
      demand_drivers: "Patient volume, specialist clinic traffic, ER visits",
      friction_points: "Patient experience, wayfinding, peak congestion",
      notes: "Validation program reform can recover $300K+ annually",
      featured: false,
      slug: "dallas-medical-district-hospital",
    },
    {
      property_name: "South Congress Austin Mixed-Use",
      city: "Austin",
      metro: "Austin-Round Rock-Georgetown",
      state: "TX",
      zip: "78704",
      property_type: "Commercial Real Estate",
      sub_type: "Mixed-Use Retail/Office",
      ownership_type: "Private Developer",
      parking_type: "Surface Lot",
      management_model: "Self-Managed",
      payment_model: "Currently Free",
      estimated_revenue_potential: "$150K-$400K annually if monetized",
      demand_drivers: "Entertainment district, restaurant traffic, tech office proximity",
      friction_points: "Community pushback on paid parking, enforcement logistics",
      notes: "High opportunity - currently leaving significant revenue on the table",
      featured: true,
      slug: "south-congress-austin-mixed-use",
    },
    {
      property_name: "Austin Domain Retail Center",
      city: "Austin",
      metro: "Austin-Round Rock-Georgetown",
      state: "TX",
      zip: "78758",
      property_type: "Commercial Real Estate",
      sub_type: "Lifestyle Retail",
      ownership_type: "REIT",
      parking_type: "Surface and Structured",
      management_model: "Outsourced",
      payment_model: "Validated - Free with Retail Purchase",
      estimated_revenue_potential: "$400K-$700K if validation reformed",
      demand_drivers: "High-end retail, entertainment, restaurant traffic",
      friction_points: "Tenant validation program costs, competitor free parking",
      notes: "Validation reform and event pricing can improve NOI meaningfully",
      featured: false,
      slug: "austin-domain-retail-center",
    },
    {
      property_name: "Houston Airport Area Hotel Portfolio",
      city: "Houston",
      metro: "Houston-The Woodlands-Sugar Land",
      state: "TX",
      zip: "77032",
      property_type: "Hotel",
      sub_type: "Select-Service",
      ownership_type: "Private Ownership Group",
      parking_type: "Surface Lot",
      management_model: "Self-Managed",
      payment_model: "Currently Free",
      estimated_revenue_potential: "$120K-$280K annually if monetized",
      demand_drivers: "Airport long-term parking demand, business travel, oil/gas contractors",
      friction_points: "Guest experience expectations, competitive airport parking nearby",
      notes: "Park-and-fly demand creates opportunity for monetization with shuttle service",
      featured: false,
      slug: "houston-airport-area-hotel-portfolio",
    },
  ]).onConflictDoNothing();

  console.log("Seeding vendors...");

  await db.insert(vendorsTable).values([
    {
      company_name: "Perfect Parking",
      category: "Parking Management Operator",
      service_area: "Texas Statewide",
      short_description: "Texas-focused full-service parking management and revenue optimization for hotels, hospitals, and commercial properties. Expert in outsourced operations, revenue analysis, and enforcement strategy.",
      website: "https://texasparkingrevenue.com/parking-revenue-analysis",
      featured: true,
      slug: "perfect-parking",
    },
    {
      company_name: "SKIDATA",
      category: "Access Control & Technology",
      service_area: "National",
      short_description: "Enterprise parking access and revenue control systems. Gated entry/exit, PARCS equipment, and revenue management software.",
      website: "https://skidata.com",
      featured: false,
      slug: "skidata",
    },
    {
      company_name: "ParkWhiz / Arrive",
      category: "Parking Technology & Marketplace",
      service_area: "National",
      short_description: "Digital parking marketplace and revenue management platform for operators seeking to maximize transient revenue through online channels.",
      website: "https://arrive.com",
      featured: false,
      slug: "parkwhiz-arrive",
    },
    {
      company_name: "T2 Systems",
      category: "Parking Technology & Software",
      service_area: "National",
      short_description: "Comprehensive parking management software including permit management, enforcement, payment processing, and analytics for campus and municipal operators.",
      website: "https://t2systems.com",
      featured: false,
      slug: "t2-systems",
    },
    {
      company_name: "IPS Group",
      category: "Smart Parking & Meters",
      service_area: "National",
      short_description: "Wireless parking meters, pay stations, and smart enforcement solutions for surface lots and street parking monetization.",
      website: "https://ipsgroupinc.com",
      featured: false,
      slug: "ips-group",
    },
    {
      company_name: "Parkeon / Flowbird",
      category: "Payment & Access Technology",
      service_area: "National",
      short_description: "Multi-space pay stations, mobile payment integration, and parking guidance systems for modern parking operations.",
      website: "https://flowbird.group",
      featured: false,
      slug: "flowbird",
    },
    {
      company_name: "Parking Network Texas",
      category: "Industry Association",
      service_area: "Texas Statewide",
      short_description: "Texas-based parking industry network connecting operators, owners, and vendors for education, networking, and best practice sharing.",
      website: "#",
      featured: false,
      slug: "parking-network-texas",
    },
  ]).onConflictDoNothing();

  console.log("Seed complete.");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
